version: '3'

services:
  redis-master-1:
    image: redis:7
    container_name: redis-master-1
    ports:
      - "6379:6379"
    networks:
      - redis-net
    volumes:
      - ./data/master1:/data
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000

  redis-master-2:
    image: redis:7
    container_name: redis-master-2
    ports:
      - "6380:6379"
    networks:
      - redis-net
    volumes:
      - ./data/master2:/data
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000

  redis-master-3:
    image: redis:7
    container_name: redis-master-3
    ports:
      - "6381:6379"
    networks:
      - redis-net
    volumes:
      - ./data/master3:/data
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000

  redis-replica-1:
    image: redis:7
    container_name: redis-replica-1
    ports:
      - "6382:6379"
    networks:
      - redis-net
    volumes:
      - ./data/replica1:/data
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000

  redis-replica-2:
    image: redis:7
    container_name: redis-replica-2
    ports:
      - "6383:6379"
    networks:
      - redis-net
    volumes:
      - ./data/replica2:/data
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000

  redis-replica-3:
    image: redis:7
    container_name: redis-replica-3
    ports:
      - "6384:6379"
    networks:
      - redis-net
    volumes:
      - ./data/replica3:/data
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000

networks:
  redis-net:
    driver: bridge

